### ISSUE TITLE
"statuses_user_timeline" doesn't work on Android(Nexus4  Android Version 4.4.4).

### ISSUE THREAD

**Issue by gekkoukisi** [mogya/tm_twitter_api#4]
I saw error that 

   " [WARN] :   DefaultRequestDirector: Authentication error: Unable to respond to any of these challenges: {}
    [WARN] :   IdleConnectionHandler: Removing a connection that never existed!
    [ERROR] :  TiHttpClient: (TiHttpClient-3) [5847,32038] HTTP Error (org.apache.http.client.HttpResponseException): Authorization Required
    [ERROR] :  TiHttpClient: org.apache.http.client.HttpResponseException: Authorization Required
    [ERROR] :  TiHttpClient:    at ti.modules.titanium.network.TiHTTPClient$LocalResponseHandler.handleResponse(TiHTTPClient.java:275)
    [ERROR] :  TiHttpClient:    at ti.modules.titanium.network.TiHTTPClient$LocalResponseHandler.handleResponse(TiHTTPClient.java:219)
    [ERROR] :  TiHttpClient:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:657)
    [ERROR] :  TiHttpClient:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:637)
    [ERROR] :  TiHttpClient:    at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1334)
    [ERROR] :  TiHttpClient:    at java.lang.Thread.run(Thread.java:841)
    [ERROR] :  XMLModule: (KrollRuntimeThread) [11,32049] Error parsing XML
    [ERROR] :  XMLModule: org.xml.sax.SAXParseException: Unexpected token (position:TEXT {"errors":[{"mes...@1:64 in java.io.InputStreamReader@4298f458)
    [ERROR] :  XMLModule:   at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
    [ERROR] :  XMLModule:   at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
    [ERROR] :  XMLModule:   at ti.modules.titanium.xml.XMLModule.parse(XMLModule.java:82)
    [ERROR] :  XMLModule:   at ti.modules.titanium.xml.XMLModule.parse(XMLModule.java:68)
    [ERROR] :  XMLModule:   at ti.modules.titanium.network.TiHTTPClient.getResponseXML(TiHTTPClient.java:706)
    [ERROR] :  XMLModule:   at ti.modules.titanium.network.HTTPClientProxy.getResponseXML(HTTPClientProxy.java:107)
    [ERROR] :  XMLModule:   at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
    [ERROR] :  XMLModule:   at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
    [ERROR] :  XMLModule:   at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1121)
    [ERROR] :  XMLModule:   at android.os.Handler.dispatchMessage(Handler.java:98)
    [ERROR] :  XMLModule:   at android.os.Looper.loop(Looper.java:136)
    [ERROR] :  XMLModule:   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
    [ERROR] :  TiHttpClient: (KrollRuntimeThread) [1,32050] Error parsing XML
    [ERROR] :  TiHttpClient: org.xml.sax.SAXParseException: Unexpected token (position:TEXT {"errors":[{"mes...@1:64 in java.io.InputStreamReader@4298f458)
    [ERROR] :  TiHttpClient:    at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
    [ERROR] :  TiHttpClient:    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
    [ERROR] :  TiHttpClient:    at ti.modules.titanium.xml.XMLModule.parse(XMLModule.java:82)
    [ERROR] :  TiHttpClient:    at ti.modules.titanium.xml.XMLModule.parse(XMLModule.java:68)
    [ERROR] :  TiHttpClient:    at ti.modules.titanium.network.TiHTTPClient.getResponseXML(TiHTTPClient.java:706)
    [ERROR] :  TiHttpClient:    at ti.modules.titanium.network.HTTPClientProxy.getResponseXML(HTTPClientProxy.java:107)
    [ERROR] :  TiHttpClient:    at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
    [ERROR] :  TiHttpClient:    at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
    [ERROR] :  TiHttpClient:    at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1121)
    [ERROR] :  TiHttpClient:    at android.os.Handler.dispatchMessage(Handler.java:98)
    [ERROR] :  TiHttpClient:    at android.os.Looper.loop(Looper.java:136)
    [ERROR] :  TiHttpClient:    at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112) "

when i tried using "statuses_user_timeline" method on Android.

Please give me some advice m_ _m  .

**Comment by mogya** [comment]
Hi,

Unfortunately, tm_twitter_api is not maintained anymore.
Why don't you try TiSocial?
https://github.com/viezel/TiSocial.Framework

2015-01-21 12:41 GMT+09:00 gekkoukisi notifications@github.com:

> I saw error that
> 
> " [WARN] : DefaultRequestDirector: Authentication error: Unable to respond
> to any of these challenges: {}
> [WARN] : IdleConnectionHandler: Removing a connection that never existed!
> [ERROR] : TiHttpClient: (TiHttpClient-3) [5847,32038] HTTP Error
> (org.apache.http.client.HttpResponseException): Authorization Required
> [ERROR] : TiHttpClient: org.apache.http.client.HttpResponseException:
> Authorization Required
> [ERROR] : TiHttpClient: at
> ti.modules.titanium.network.TiHTTPClient$LocalResponseHandler.handleResponse(TiHTTPClient.java:275)
> [ERROR] : TiHttpClient: at
> ti.modules.titanium.network.TiHTTPClient$LocalResponseHandler.handleResponse(TiHTTPClient.java:219)
> [ERROR] : TiHttpClient: at
> org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:657)
> [ERROR] : TiHttpClient: at
> org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:637)
> [ERROR] : TiHttpClient: at
> ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1334)
> [ERROR] : TiHttpClient: at java.lang.Thread.run(Thread.java:841)
> [ERROR] : XMLModule: (KrollRuntimeThread) [11,32049] Error parsing XML
> [ERROR] : XMLModule: org.xml.sax.SAXParseException: Unexpected token
> (position:TEXT {"errors":[{"mes...@1 https://github.com/1:64 in
> java.io.InputStreamReader@4298f45
> https://github.com/java.io.InputStreamReader/tm_twitter_api/commit/4298f458
> )
> [ERROR] : XMLModule: at
> org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
> [ERROR] : XMLModule: at
> javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
> [ERROR] : XMLModule: at
> ti.modules.titanium.xml.XMLModule.parse(XMLModule.java:82)
> [ERROR] : XMLModule: at
> ti.modules.titanium.xml.XMLModule.parse(XMLModule.java:68)
> [ERROR] : XMLModule: at
> ti.modules.titanium.network.TiHTTPClient.getResponseXML(TiHTTPClient.java:706)
> [ERROR] : XMLModule: at
> ti.modules.titanium.network.HTTPClientProxy.getResponseXML(HTTPClientProxy.java:107)
> [ERROR] : XMLModule: at
> org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
> [ERROR] : XMLModule: at
> org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
> [ERROR] : XMLModule: at
> org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1121)
> [ERROR] : XMLModule: at android.os.Handler.dispatchMessage(Handler.java:98)
> [ERROR] : XMLModule: at android.os.Looper.loop(Looper.java:136)
> [ERROR] : XMLModule: at
> org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
> [ERROR] : TiHttpClient: (KrollRuntimeThread) [1,32050] Error parsing XML
> [ERROR] : TiHttpClient: org.xml.sax.SAXParseException: Unexpected token
> (position:TEXT {"errors":[{"mes...@1 https://github.com/1:64 in
> java.io.InputStreamReader@4298f45
> https://github.com/java.io.InputStreamReader/tm_twitter_api/commit/4298f458
> )
> [ERROR] : TiHttpClient: at
> org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
> [ERROR] : TiHttpClient: at
> javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:107)
> [ERROR] : TiHttpClient: at
> ti.modules.titanium.xml.XMLModule.parse(XMLModule.java:82)
> [ERROR] : TiHttpClient: at
> ti.modules.titanium.xml.XMLModule.parse(XMLModule.java:68)
> [ERROR] : TiHttpClient: at
> ti.modules.titanium.network.TiHTTPClient.getResponseXML(TiHTTPClient.java:706)
> [ERROR] : TiHttpClient: at
> ti.modules.titanium.network.HTTPClientProxy.getResponseXML(HTTPClientProxy.java:107)
> [ERROR] : TiHttpClient: at
> org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
> [ERROR] : TiHttpClient: at
> org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
> [ERROR] : TiHttpClient: at
> org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1121)
> [ERROR] : TiHttpClient: at
> android.os.Handler.dispatchMessage(Handler.java:98)
> [ERROR] : TiHttpClient: at android.os.Looper.loop(Looper.java:136)
> [ERROR] : TiHttpClient: at
> org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
> "
> 
> when i tried using "statuses_user_timeline" method on Android.
> 
> Please give me some advice m_ _m .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mogya/tm_twitter_api/issues/4.

## 

古川 大輔（Furukawa Daisuke）
ホームページ「もぎゃんらんど」 http://mogya.com
街の電源検索サイト「モバイラーズオアシス」http://oasis.mogya.com/

**Comment by gekkoukisi** [comment]
I didn't know that!
I'll try it!
Thank you !! ^^
